
### SHOW ALL TRIPS
GET http://localhost:8000/api/trips/
Content-Type: application/json
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImV4cCI6MTYyNDI3MjQ1OX0.sm0c7ZjG3Dy5Vqf-jlAE4GlyHRWzwLS-VEeMPskNnfI



### SHOW one TRIP
GET http://localhost:8000/api/trips/10/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImV4cCI6MTYyNDI3MjQ1OX0.sm0c7ZjG3Dy5Vqf-jlAE4GlyHRWzwLS-VEeMPskNnfI



### DELETE ONE TRIP BY ID
DELETE http://localhost:8000/api/trips/1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImV4cCI6MTYyNDI3MjQ1OX0.sm0c7ZjG3Dy5Vqf-jlAE4GlyHRWzwLS-VEeMPskNnfI


### CREATE A TRIP
POST http://localhost:8000/api/trips/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMsImV4cCI6MTYyNDQ1NDA4OX0.LtogV2-_osm8oa0C0U6ojyqClHCum4Vq6QDWBGPnx64

{
  "name": "Trip to Paris",
  "latitudeLongitude": [7.43861, 46.95083],
  "description": "Great trip",
  "image": "image.png"
}


### EDIT A TRIP
PUT http://localhost:8000/api/trips/2/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImV4cCI6MTYyNDI3MjQ1OX0.sm0c7ZjG3Dy5Vqf-jlAE4GlyHRWzwLS-VEeMPskNnfI

{
  "name": "Trip to London",
  "location_string": " London, UK",
  "description": "Great trip, really",
  "image": "image.png"
}


### COMMENT ON A TRIP
POST http://localhost:8000/api/trips/10/comments/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImV4cCI6MTYyNDI3MjQ1OX0.sm0c7ZjG3Dy5Vqf-jlAE4GlyHRWzwLS-VEeMPskNnfI


{
  "content": "cool trip"
}


### DELETE A COMMENT
DELETE http://localhost:8000/api/trips/2/comments/1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImV4cCI6MTYyNDI3MjQ1OX0.sm0c7ZjG3Dy5Vqf-jlAE4GlyHRWzwLS-VEeMPskNnfI


### TRIP LIKE VIEW
POST http://localhost:8000/api/trips/10/like/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwLCJleHAiOjE2MjQ4Njk4MTh9.al8FSKag25MQrT3zW-9mjRFQftEC1h5UJneD51df1Lk




### REGISTER A USER

POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{ "username": "kat2",
  "email": "kat@email.com2",
  "profileImage": "image.jpg",
  "userCity": "London",
  "userCountry": "UK",
  "password": "pass",
  "passwordConfirmation": "pass"

}

  # "profileImage": "image.jpg",
  # "userCity": "London",

### LOGIN A USER

POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "email": "katja@kat.com",
  "password": "pass"

}

### USER PROFILE VIEW

GET http://localhost:8000/api/auth/profile/6
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMsImV4cCI6MTYyNDQ1OTE2Mn0.lN1bAyoBCn2km-svA9aATgfbPSct8dvMWAgFmQ_5fuw


### EDIT PROFILE VIEW
PUT http://localhost:8000/api/auth/profile/6/edit/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjYsImV4cCI6MTYyNTUwMjE3MX0.Z7TL6pwiEmYCA8-xIyJSxKoCO22CrcQO42p_2FdYEoI

{

  "status": "Hi London how are you"



}

### EDIT PROFILE IMAG VIEW
PUT http://localhost:8000/api/auth/profile/6/edit/image/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjYsImV4cCI6MTYyNTUwMjE3MX0.Z7TL6pwiEmYCA8-xIyJSxKoCO22CrcQO42p_2FdYEoI

{


  "profile_image": "newimage.jpg"



}



### 
GET https://travel-advisor.p.rapidapi.com/attractions/list-by-latlng
Content-Type: application/json
x-rapidapi-key: 97dc91ee1amsh66c5d649a7ac4fcp19c6f5jsn216d8806b1bc
x-rapidapi-host: 'travel-advisor.p.rapidapi.com


{
  "longitude": "50",
  "latitude": "2"

}

### VIEW ALL LISTS
GET http://localhost:8000/api/trips/lists/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImV4cCI6MTYyNDI3MjQ1OX0.sm0c7ZjG3Dy5Vqf-jlAE4GlyHRWzwLS-VEeMPskNnfI


### VIEW ONE LIST
GET http://localhost:8000/api/trips/lists/4/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwLCJleHAiOjE2MjQ4Njk4MTh9.al8FSKag25MQrT3zW-9mjRFQftEC1h5UJneD51df1Lk


### RENAME ONE LIST AND/ OR CHANGE PRIVACY SETTINGS
PUT http://localhost:8000/api/trips/lists/2/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImV4cCI6MTYyNDI3MjQ1OX0.sm0c7ZjG3Dy5Vqf-jlAE4GlyHRWzwLS-VEeMPskNnfI

{
  "list_name": "Renamed List Yes again once more hey",
  "is_public": "True"

}

### DELETE ONE LIST
DELETE  http://localhost:8000/api/trips/lists/1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImV4cCI6MTYyNDI3MjQ1OX0.sm0c7ZjG3Dy5Vqf-jlAE4GlyHRWzwLS-VEeMPskNnfI




### START A NEW LIST
POST http://localhost:8000/api/trips/lists/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwLCJleHAiOjE2MjQ4Njk4MTh9.al8FSKag25MQrT3zW-9mjRFQftEC1h5UJneD51df1Lk

{
  "list_name": "Winter",
  "isPublic": "True"

}

### ADD A TRIP TO A LIST TOGGLE TO REMOVE FROM LIST IF TRIP ALREADY EXISTS
POST http://localhost:8000/api/trips/4/list/16/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwLCJleHAiOjE2MjQ4Njk4MTh9.al8FSKag25MQrT3zW-9mjRFQftEC1h5UJneD51df1Lk

