# Generated by Django 3.2.4 on 2021-06-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertriplist',
            name='is_public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
