# Generated by Django 3.2.4 on 2021-06-14 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0002_usertriplist_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='listed_by',
            field=models.ManyToManyField(blank=True, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertriplist',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='TripLists', to='trips.Trip'),
        ),
    ]
