# Generated by Django 3.2.4 on 2021-06-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20210614_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertriplist',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='trips', to='trips.Trip'),
        ),
    ]
