# Generated by Django 3.2.4 on 2021-06-16 13:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_latitude_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='latitude_longitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=50), size=None),
        ),
    ]
