# Generated by Django 3.2.4 on 2021-06-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_latitude_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='location_string',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='open_now_text',
        ),
    ]
